import React, { createContext, useContext, useState } from 'react';

export type Language = 'en' | 'ko';

export interface TranslationDictionary {
  [key: string]: {
    en: string;
    ko: string;
  };
}

export const translations: TranslationDictionary = {
  // Navigation & Tabs
  dashboard: { en: 'Dashboard', ko: '대시보드' },
  upload: { en: 'Analyze', ko: '분석하기' },
  history: { en: 'History', ko: '기록' },
  pets: { en: 'My Pets', ko: '반려동물' },
  settings: { en: 'Settings', ko: '설정' },
  reminders: { en: 'Reminders', ko: '알림' },
  challenges: { en: 'Challenges', ko: '챌린지' },

  // General App Branding
  appName: { en: 'Pawsitive Behavior', ko: '파지티브 비헤이비어 (Pawsitive Behavior)' },
  aiBehaviorist: { en: 'AI Behaviorist', ko: 'AI 행동분석가' },
  proTier: { en: 'Pro Tier', ko: '프로 등급' },
  freeTier: { en: 'Free Tier', ko: '무료 등급' },
  logout: { en: 'Log Out', ko: '로그아웃' },
  saving: { en: 'Saving...', ko: '저장 중...' },

  // Dashboard Tab
  dayStreak: { en: '{streak} Day Streak', ko: '{streak}일 연속 기록' },
  dailyGoalMet: { en: 'Daily Goal Met', ko: '오늘의 목표 달성' },
  streakActiveDesc: { en: "Great job! You've completed your training for today.", ko: '잘하셨습니다! 오늘의 훈련/분석을 완료하셨습니다.' },
  streakInactiveDesc: { en: 'Keep the momentum going! Upload a video to maintain your streak.', ko: '흐름을 유지하세요! 스트릭을 유지하려면 영상을 업로드하세요.' },
  welcomeBack: { en: 'Welcome back, {name}!', ko: '돌아온 것을 환영합니다, {name}님!' },
  quickStats: { en: 'Quick Stats', ko: '빠른 통계' },
  totalAnalyses: { en: 'Total Analyses', ko: '총 분석 횟수' },
  activeChallenges: { en: 'Active Challenges', ko: '진행 중인 챌린지' },
  proMemberSince: { en: 'Pro Member Since', ko: '프로 멤버 가입일' },
  freeMemberLimit: { en: 'Free analyses left this month: {left}', ko: '이번 달 남은 무료 분석: {left}회' },
  currentStreak: { en: 'Current Streak', ko: '현재 스트릭' },
  totalSessions: { en: 'Total Sessions', ko: '총 세션 수' },
  trainingConsistency: { en: 'Training Consistency', ko: '훈련 일관성' },
  cumulativeSessions: { en: 'Cumulative training sessions over time', ko: '시간에 따른 누적 훈련 세션' },
  sessions: { en: 'Sessions', ko: '세션' },
  recentAnalyses: { en: 'Recent Analyses', ko: '최근 분석 기록' },
  viewAll: { en: 'View All', ko: '전체 보기' },
  upcomingCare: { en: 'Upcoming Care', ko: '예정된 일정' },
  allCaughtUp: { en: 'All caught up!', ko: '모두 완료했습니다!' },
  noUpcomingTasks: { en: 'No upcoming tasks for today.', ko: '오늘 예정된 일정이 없습니다.' },
  trainerStatus: { en: 'Trainer Status', ko: '트레이너 등급' },
  trainerStatusDesc: { en: 'Complete 30 sessions and unlock your pet\'s potential!', ko: '30세션을 완료하여 반려동물의 잠재력을 일깨워주세요!' },

  // Upload Tab
  analyzeBehavior: { en: 'Analyze Behavior', ko: '행동 분석하기' },
  choosePet: { en: 'Choose a Pet (Optional)', ko: '반려동물 선택 (선택 사항)' },
  noPetSelected: { en: 'No specific pet selected', ko: '반려동물 선택 안 함' },
  askQuestionPlaceholder: { en: 'Optional: Ask a specific question about this behavior...', ko: '선택 사항: 이 행동에 대해 특별히 궁금한 점을 질문해 주세요...' },
  videoUploadLabel: { en: 'Select Behavior Video', ko: '행동 분석 영상 선택' },
  audioUploadLabel: { en: 'Select Audio / Vocalization File', ko: '오디오 / 울음소리 파일 선택' },
  recordVideoLabel: { en: 'Record Video (Max 30s)', ko: '영상 직접 녹화 (최대 30초)' },
  uploadFormatDesc: { en: 'Supports MP4, MOV, WEBM, MP3, WAV up to 50MB.', ko: '최대 50MB의 MP4, MOV, WEBM, MP3, WAV 파일을 지원합니다.' },
  analyzingBehavior: { en: 'Analyzing Behavior...', ko: '행동 분석 중...' },
  preparingMedia: { en: 'Preparing media...', ko: '미디어 준비 중...' },
  processingAnalysis: { en: 'Processing analysis...', ko: '분석 처리 중...' },
  savingResults: { en: 'Saving results...', ko: '결과 저장 중...' },
  savingMediaCloud: { en: 'Saving media to cloud...', ko: '미디어를 클라우드에 저장 중...' },
  complete: { en: 'Complete!', ko: '완료!' },
  limitReached: { en: 'Limit Reached', ko: '한도 도달' },
  tryAnotherVideo: { en: 'Try Another Video', ko: '다른 영상으로 시도하기' },

  // Analysis Report
  analysisReport: { en: 'Analysis Report', ko: '행동 분석 보고서' },
  nonPetWarningTitle: { en: 'Analysis Limited', ko: '분석 제한됨' },
  nonPetWarningDesc: { en: 'Our AI behaviorist only specializes in pet behavior. This media does not appear to contain a pet.', ko: '저희 AI 행동분석가는 반려동물의 행동 분석만을 전문으로 합니다. 이 미디어에는 반려동물이 포함되어 있지 않은 것 같습니다.' },
  primaryEmotionalState: { en: 'Primary Emotional State', ko: '주요 감정 상태' },
  detailedObservations: { en: 'Detailed Observations', ko: '상세 관찰 결과' },
  recommendedActionSteps: { en: 'Recommended Action Steps', ko: '추천 실천 조치' },
  trainingChallengeCardTitle: { en: '7-Day Training Challenge', ko: '7일 맞춤 훈련 챌린지' },
  startChallenge: { en: 'Start 7-Day Challenge', ko: '7일 챌린지 시작하기' },
  challengeActive: { en: 'Active Challenge', ko: '진행 중인 챌린지' },
  professionalDisclaimer: { en: 'Professional Disclaimer', ko: '전문적 면책 조항' },
  disclaimerText: { en: 'This analysis is generated by AI and is for educational/informational purposes only. It is not a substitute for professional veterinary diagnostics, medical advice, or professional behaviorist evaluation.', ko: '이 분석은 AI에 의해 생성되었으며 교육 및 정보 제공 목적으로만 사용됩니다. 전문적인 수의학적 진단, 진료 또는 전문 행동분석가의 평가를 대신할 수 없습니다.' },
  
  // History Tab
  previousAnalyses: { en: 'Previous Analyses', ko: '이전 분석 기록' },
  noAnalysesYet: { en: 'No analyses yet. Start by uploading a video of your pet!', ko: '아직 분석 기록이 없습니다. 반려동물의 영상을 업로드하여 시작해 보세요!' },
  viewReport: { en: 'View Report', ko: '보고서 보기' },
  chatWithBehaviorist: { en: 'Chat with AI Behaviorist', ko: 'AI 행동분석가와 대화하기' },
  chatPlaceholder: { en: 'Ask a follow-up question about this behavior...', ko: '이 행동에 대해 추가로 궁금한 점을 질문해 주세요...' },
  chatDisclaimer: { en: 'AI behavioral consultations are support tools. Always consult a veterinarian for health issues.', ko: 'AI 행동 상담은 보조적인 도구입니다. 건강에 문제가 있을 경우 반드시 수의사와 상담하십시오.' },

  // My Pets Tab
  addPet: { en: 'Add Pet Profile', ko: '반려동물 프로필 추가' },
  petName: { en: 'Pet Name', ko: '반려동물 이름' },
  species: { en: 'Species', ko: '종류' },
  breed: { en: 'Breed / Variety', ko: '품종 / 종류 상세' },
  age: { en: 'Age', ko: '나이' },
  personality: { en: 'Personality / Quirks', ko: '성격 / 독특한 습성' },
  savePetProfile: { en: 'Save Pet Profile', ko: '프로필 저장' },
  petProfiles: { en: 'Pet Profiles', ko: '반려동물 프로필 목록' },
  noPetsYet: { en: 'No pets added yet. Add a pet to get personalized analysis context!', ko: '등록된 반려동물이 없습니다. 맞춤형 분석을 위해 반려동물을 추가해 보세요!' },
  deletePetConfirm: { en: 'Are you sure you want to delete this pet profile?', ko: '이 반려동물 프로필을 삭제하시겠습니까?' },

  // Challenges Tab
  sevenDayChallenges: { en: '7-Day Challenges', ko: '7일 맞춤 훈련 챌린지' },
  activeTrainingChallenges: { en: 'Active Training Challenges', ko: '진행 중인 훈련 챌린지' },
  noActiveChallenges: { en: 'No active training challenges yet. Complete a behavior analysis to trigger a custom 7-day challenge!', ko: '아직 진행 중인 훈련 챌린지가 없습니다. 행동 분석을 완료하여 7일 맞춤형 챌린지를 시작해 보세요!' },
  dayCount: { en: 'Day {day}', ko: '{day}일차' },
  completeDay: { en: 'Complete Day {day}', ko: '{day}일차 완료' },
  completed: { en: 'Completed', ko: '완료됨' },

  // Reminders Tab
  careReminders: { en: 'Care Reminders', ko: '케어 알림' },
  addReminder: { en: 'Add Care Reminder', ko: '알림 추가' },
  reminderTitle: { en: 'Reminder Title', ko: '알림 제목' },
  reminderTime: { en: 'Time', ko: '시간' },
  reminderFrequency: { en: 'Frequency', ko: '빈도' },
  daily: { en: 'Daily', ko: '매일' },
  weekly: { en: 'Weekly', ko: '매주' },
  monthly: { en: 'Monthly', ko: '매월' },
  saveReminder: { en: 'Save Reminder', ko: '알림 저장' },
  noRemindersYet: { en: 'No care reminders yet. Stay on top of your pet\'s health!', ko: '설정된 알림이 없습니다. 반려동물의 건강 관리를 시작해 보세요!' },

  // Settings Tab
  accountSettings: { en: 'Account Settings', ko: '계정 설정' },
  proActiveTitle: { en: 'Pro Membership Active', ko: '프로 멤버십 활성화됨' },
  proActiveDesc: { en: 'You have unlimited access to all AI Behaviorist features.', ko: '모든 AI 행동분석가 기능에 대한 무제한 권한을 보유 중입니다.' },
  profileInfo: { en: 'Profile Information', ko: '프로필 정보' },
  profilePic: { en: 'Profile Picture', ko: '프로필 사진' },
  profilePicDesc: { en: 'Click the image to upload a new one.', ko: '이미지를 클릭하여 새 사진을 업로드하세요.' },
  displayName: { en: 'Display Name', ko: '닉네임' },
  emailAddress: { en: 'Email Address', ko: '이메일 주소' },
  emailCantBeChanged: { en: 'Email cannot be changed currently.', ko: '이메일 주소는 현재 변경할 수 없습니다.' },
  updateProfile: { en: 'Update Profile', ko: '프로필 업데이트' },
  subscriptionPlan: { en: 'Subscription Plan', ko: '구독 플랜' },
  proBehaviorPro: { en: 'Pawsitive Behavior Pro', ko: '파지티브 비헤이비어 프로 (Pro)' },
  proBehaviorFree: { en: 'Pawsitive Behavior Free', ko: '파지티브 비헤이비어 프리 (Free)' },
  freeLimitDesc: { en: 'You have used {used}/3 free analyses. Upgrade for unlimited access.', ko: '3회의 무료 분석 중 {used}회를 사용하셨습니다. 무제한 분석을 위해 업그레이드해 보세요.' },
  languageSettings: { en: 'Language / 언어', ko: 'Language / 언어' },
  selectLanguage: { en: 'Select Language', ko: '언어 선택' },
  upgradeToProBtn: { en: 'Upgrade to Pro', ko: '프로(Pro)로 업그레이드' },

  // Sign In / Auth Screen
  signInWelcome: { en: 'Welcome to Pawsitive Behavior', ko: '파지티브 비헤이비어에 오신 것을 환영합니다' },
  signInGoogleDesc: { en: 'Sign in securely with Google to analyze, track, and improve your pet\'s behavior and wellness.', ko: '구글 계정으로 안전하게 로그인하여 반려동물의 행동과 건강을 분석하고 개선해 보세요.' },
  signingIn: { en: 'Signing in...', ko: '로그인 중...' },
  signInWithGoogle: { en: 'Sign in with Google', ko: 'Google 계정으로 로그인' },
  commercialStoreNotice: { 
    en: "Premium features require a subscription. Payments are processed securely through your device's app store (Apple App Store or Google Play). Subscriptions automatically renew unless canceled at least 24 hours before the end of the current period.", 
    ko: "프리미엄 기능은 구독이 필요합니다. 결제는 기기의 앱 스토어(Apple App Store 또는 Google Play)를 통해 안전하게 처리됩니다. 현재 기간이 끝나기 최소 24시간 전에 취소하지 않으면 구독이 자동으로 갱신됩니다." 
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof typeof translations, replacements?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('pawsitive_lang');
    if (saved === 'en' || saved === 'ko') return saved;
    
    // Auto-detect system language
    const sysLang = navigator.language.toLowerCase();
    if (sysLang.startsWith('ko')) return 'ko';
    return 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('pawsitive_lang', lang);
  };

  const t = (key: keyof typeof translations, replacements?: Record<string, string | number>): string => {
    const entry = translations[key];
    if (!entry) {
      console.warn(`Translation key not found: ${key}`);
      return String(key);
    }
    
    let text = entry[language] || entry['en'] || String(key);
    
    if (replacements) {
      Object.entries(replacements).forEach(([k, val]) => {
        text = text.replace(`{${k}}`, String(val));
      });
    }
    
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
